const String kprojectURL = 'https://gvabynjxjdnwjspdsahd.supabase.co';
const String kApiKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2YWJ5bmp4amRud2pzcGRzYWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDc5MTY0MDAsImV4cCI6MjAyMzQ5MjQwMH0.DDS-yDwBpiLH9RyrR94Mq72_1NTDmgejEIJ1f_RcHDg';
